
services:
  dhcp-server:
    image: jpillora/dnsmasq
    container_name: dhcp-server
    networks:
      custom-network:
        ipv4_address: 192.168.1.2
    command: ["-d", "--dhcp-range=192.168.1.10,192.168.1.100,12h"]
    
  client:
    image: alpine
    container_name: client1
    networks:
      custom-network:
        ipv4_address: 192.168.1.3
    command: ["sleep","infinity"]
  
  client2:
    image: alpine
    container_name: client2
    networks:
      custom-network:
    command: ["sleep","infinity"]

networks:
  custom-network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"
