services:
  dhcp-server:
    image: jpillora/dnsmasq
    container_name: dhcp-server
    networks:
      subnet1:
        ipv4_address: 192.168.1.2
    command: ["-d", "--dhcp-range=192.168.1.10,192.168.1.100,12h"]
    
  client1:
    image: alpine
    container_name: client1
    networks:
      subnet1:
    command: ["sleep", "infinity"]
  
  client2:
    image: alpine
    container_name: client2
    networks:
      subnet2:
    command: ["sleep", "infinity"]

  router:
    image: alpine
    container_name: router
    privileged: true
    networks:
      subnet1:
      subnet2:
    command: ["sh", "-c", "apk add iproute2 && sysctl -w net.ipv4.ip_forward=1 && sleep infinity"]

networks:
  subnet1:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: 192.168.1.1
  subnet2:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.2.0/24"
